<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Arick" failures="1" tests="3" name="WhiteTower" time="212.267" errors="0" timestamp="17 ago. 2023 01:54:06 GMT">
  <testcase classname="TestTodoMVC.MyTestingClass" name="testcase1" time="0.032">
    <failure type="java.lang.AssertionError" message="ToDo 3 is not in third position expected [ToDo 3] but found [ToDo 4]">
      <![CDATA[java.lang.AssertionError: ToDo 3 is not in third position expected [ToDo 3] but found [ToDo 4]
at TestTodoMVC.MyTestingClass.testcase1(MyTestingClass.java:93)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <testcase classname="TestTodoMVC.MyTestingClass" name="testcase2" time="3.27"/>
  <testcase classname="TestTodoMVC.MyTestingClass" name="testcase3" time="6.183"/>
</testsuite> <!-- WhiteTower -->
